services:
  # Node exporter sa textfile collector
  node-exporter:
    image: prom/node-exporter:v1.10.2
    container_name: node-exporter
    ports:
      - "9100:9100"
    volumes:
      - ./exporter:/var/lib/node_exporter:rw
    command:
      - '--collector.textfile.directory=/var/lib/node_exporter'
      - '--collector.textfile'
    restart: unless-stopped
  
  # Prometheus
  prometheus:
    image: prom/prometheus:v3.7.2
    container_name: prometheus
    ports:
      - "9090:9090"
    user: "65534:65534"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules:/etc/prometheus/rules
      - ./prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30m'
      - '--web.enable-lifecycle'
    restart: unless-stopped
  
  # Grafana
  grafana:
    image: grafana/grafana:12.2.1
    container_name: grafana
    user: "472:472"
    ports:
      - "3500:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - ./grafana:/var/lib/grafana
      - ./dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped
